---
- name: Install Nginx
  hosts: web
  become: yes

  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install nginx
      apt:
        name: nginx
        state: latest

    - name: Ensure nginx is running
      service:
        name: nginx
        state: started
        enabled: yes