---
- name: Practice on Ansible
  hosts: dev
  user: ansible
  become: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: Install nginx
      command: apt install nginx -y

    - name: Start nginx
      command: systemctl start nginx
      
    - name: Check nginx version
      command: nginx -v    